[package]
name = "bpdetect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.1"
quizx = { git = "https://github.com/Quantomatic/quizx" }
rustc-hash = "1.1.0"

